### ISSUE TITLE
Please support Java 6

### ISSUE THREAD

**Issue by sebthom** [ggeorgovassilis/spring-rest-invoker#20]
Based on the code I cannot find any compelling reason why the project is targeting Java 8 and not Java 6 as the Spring Framework itself does.

Simply by replacing the few <> diamond operators it compiles on Java 6.

Great project btw.

**Comment by ggeorgovassilis** [comment]
@sebthom done, please check

**Comment by sebthom** [comment]
Nice, thanks!
