### ISSUE TITLE
Maven artifact for version 1.5

### ISSUE THREAD

**Issue by sebthom** [ggeorgovassilis/spring-rest-invoker#23]
Hi George,
could you please publish the 1.5 release to 
https://github.com/ggeorgovassilis/spring-rest-invoker/tree/gh-pages

Thanks,
Seb

**Comment by ggeorgovassilis** [comment]
Thanks for spotting. The documentation stated a wrong branch (fixed); the proper URL is https://raw.github.com/ggeorgovassilis/spring-rest-invoker/mvn-pages/
