### ISSUE TITLE
Publish releases to official maven repo

### ISSUE THREAD

**Issue by sebthom** [ggeorgovassilis/spring-rest-invoker#24]
Via Bintray: https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/
Via Sonatype: http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/

**Comment by ggeorgovassilis** [comment]
Won't fix. Maintainers welcome.

**Comment by sebthom** [comment]
I don't think it is a good idea if other people would upload your artifact under your groupId and artifactId.

If the official repo is too much effort because it requires signing the artifacts etc. you can also simply upload them to JCenter as part of the release process. It is as simple as uploading it to your gh-pages.

You create yourself a bintray account, create a new maven repo in the UI, create an API key, and add this to your maven config:

```xml
    <!-- pom.xml -->
    <distributionManagement>
        <downloadUrl>https://github.com/sebthom/jstuff/releases/</downloadUrl>
        <repository>
            <id>bintray</id>
            <url>https://api.bintray.com/maven/YOUR_USER/YOUR_REPO/spring-rest-invoker/;publish=1</url>
        </repository>
    </distributionManagement>

    <!-- settings.xml -->
    <server>
        <id>bintray</id>
        <username>YOUR_USER</username>
        <password>YOUR_API_KEY</password>
    </server>
```

Once you published your first artifact, click the "Add to JCenter" in the UI of your package and you are done.

This is a one-time setup. You never have to touch it again.

**Comment by ggeorgovassilis** [comment]
Now that I know how to do it I'm reopening this issue

**Comment by ggeorgovassilis** [comment]
<dependency>
    <groupId>com.github.ggeorgovassilis</groupId>
    <artifactId>spring-rest-invoker</artifactId>
    <version>1.7.0</version>
</dependency>
