### ISSUE TITLE
Duplicate projet of (Spring Cloud) OpenFeign?

### ISSUE THREAD

**Issue by mxmlnglt** [ggeorgovassilis/spring-rest-invoker#37]
Hello,

I came across this project after reading answers on this SO question:
https://stackoverflow.com/questions/8002514/spring-mvc-annotated-controller-interface-with-pathvariable

However it seems to me this project is 100% doing the same as OpenFeign (or its integration in Spring aka "Spring Cloud OpenFeign"):

OpenFeign:
https://github.com/OpenFeign/feign

Spring Cloud OpenFeign:
https://spring.io/projects/spring-cloud-openfeign
https://github.com/spring-cloud/spring-cloud-openfeign

**Comment by ggeorgovassilis** [comment]
Hi @mxmlnglt 
This ticket doesn't report a bug or requests a feature - I'm not sure what your intention was by submitting it. Please clarify.

**Comment by mxmlnglt** [comment]
I'm questioning the use of your project in a Spring application given that the same can be done with OpenFeign, especially as both OpenFeign and Spring Cloud OpenFeign are actively maintained (which doesn't seem the case for your project; cf. https://github.com/ggeorgovassilis/spring-rest-invoker/issues )

**Comment by ggeorgovassilis** [comment]
Please suggest the content of a pull request which you would deem a satisfactory conclusion to the issue you submitted.
